
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yuoj-mysql:3306/yuoj
    username: root
    password: 123456
  # Redis 配置
  redis:
    database: 1
    host: yuoj-redis
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: yuoj-nacos:8848
  rabbitmq:
    host: yuoj-rabbitmq
    port: 5672
    password: guest
    username: guest
