# Common configuration file

spring:
  application:
    name: yuoj-backend-judge-service
  # Default dev environment
  profiles:
    active: dev
  # Support swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # Session configuration
  session:
    store-type: redis
    # 30 days expiration
    timeout: 2592000
  # Database configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuoj
    username: root
    password: 123456
  # Redis configuration
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      # Size limit
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        namespace: public
        register-enabled: true
        watch-delay: 3000
        naming-load-cache-at-start: false
        heart-beat-interval: 10000
        heart-beat-timeout: 30000
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
server:
  address: 0.0.0.0
  port: 8104
  servlet:
    context-path: /api/judge
    # Cookie 30 days expiration
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # Global logical deletion entity field name
      logic-delete-value: 1 # Logical deleted value (default is 1)
      logic-not-delete-value: 0 # Logical not deleted value (default is 0)
# Code sandbox configuration
codesandbox:
  type: thirdParty
  judge0:
    base-url: https://judge0-ce.p.rapidapi.com
    rapidapi-key: 087d919e2dmshf5f3c038d699943p1fb696jsnf1a52bbb84b2
    rapidapi-host: judge0-ce.p.rapidapi.com
    timeout: 60
    max-retries: 60
knife4j:
  enable: true